src/objects/Known__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <referenceTo>Object__c</referenceTo>
        <relationshipLabel>Known</relationshipLabel>
        <relationshipName>Known</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Known</label>
    <nameField>
        <displayFormat>K-{00000}</displayFormat>
        <label>Known Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Known</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Object__c.object
<CustomObject>
    <label>Object</label>
    <nameField>
        <label>Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Prediction__c.object
<CustomObject>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Known__c</fullName>
        <label>Known</label>
        <referenceTo>Known__c</referenceTo>
        <relationshipLabel>Predictions</relationshipLabel>
        <relationshipName>Predictions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <label>Probability</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Prediction</label>
    <nameField>
        <displayFormat>P-{00000}</displayFormat>
        <label>Prediction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Predictions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SuggestionController.cls
global class SuggestionController { 
    @AuraEnabled
    global static List<Prediction__c> getSuggestions(Id recId) {
        String objType = String.valueOf(recId.getSobjectType());
        Set<String> types = new Set<String>{'PICKLIST'};
        List<String> fields = new List<String>(ObjectUtil.getFields(types,recId.getSobjectType()).keySet());
        String query = 'SELECT ' + String.join(fields, ', ') + ' FROM ' + objType + ' LIMIT 1';
        sObject rec = Database.query(query);
        
        List<String> vals = new List<String>();
        for(String f : fields){
            vals.add((String)rec.get(f));
        }
        
        List<Prediction__c> suggestions = 
            [SELECT Known__r.Field__c, Known__r.Value__c, Probability__c, Value__c, Field__c, Id FROM Prediction__c 
             WHERE Known__r.Object__r.Name LIKE :objType AND Known__r.Field__c in :fields AND Known__r.Value__c IN :vals
             ORDER BY Probability__c DESC
            ];
        
        return filterPList(suggestions, fields, rec);
    }
    
    private static List<Prediction__c> filterPList(List<Prediction__c> preds, List<String> fields, sObject rec){
        Map<String, Prediction__c> groups = new Map<String, Prediction__c>();
        for(String f : fields){
            for(Prediction__c p : preds){
                if(p.Value__c != rec.get(f) && groups.get(p.Field__c) == null){
                    groups.put(p.Field__c, p);
                }
            }
        }
        system.debug(groups.values());
        return groups.values();
    }
}